[[target]]
address = "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"
standard_json = "boredapeyachtclub.json"
contract_name = "BoredApeYachtClub"

[target.discovery]
address = "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"
end_block = 25996062
limit = 500
