[[target]]
address = "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"
discovery_address = "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"
discovery_end_block = 25996062
discovery_limit = 500
standard_json = "boredapeyachtclub.json"
contract_name = "BoredApeYachtClub"
