[[target]]
address = "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
discovery_address = "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
discovery_end_block = 25975140
discovery_limit = 500
standard_json = "wbtc.json"
contract_name = "WrappedBitcoinWBTC"
