[[target]]
address = "0x1b0e765f6224c21223aea2af16c1c46e38885a40"
discovery_address = "0x1b0e765f6224c21223aea2af16c1c46e38885a40"
discovery_end_block = 25975138
discovery_limit = 500
standard_json = "compound-comet-rewards.json"
contract_name = "CompoundIIICometRewards"
